/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DocRouteImport } from './routes/doc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ChatChatNumberRouteImport } from './routes/chat.$chatNumber'
import { Route as DocIndexRouteImport } from './routes/doc.index'
import { Route as DocUploadRouteImport } from './routes/doc.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocRoute = DocRouteImport.update({
  id: '/doc',
  path: '/doc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatNumberRoute = ChatChatNumberRouteImport.update({
  id: '/$chatNumber',
  path: '/$chatNumber',
  getParentRoute: () => ChatRoute,
} as any)
const DocIndexRoute = DocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocRoute,
} as any)
const DocUploadRoute = DocUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DocRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/doc': typeof DocRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat/$chatNumber': typeof ChatChatNumberRoute
  '/doc/upload': typeof DocUploadRoute
  '/doc/': typeof DocIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat/$chatNumber': typeof ChatChatNumberRoute
  '/doc/upload': typeof DocUploadRoute
  '/doc': typeof DocIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/doc': typeof DocRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat/$chatNumber': typeof ChatChatNumberRoute
  '/doc/upload': typeof DocUploadRoute
  '/doc/': typeof DocIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/doc'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/chat/$chatNumber'
    | '/doc/upload'
    | '/doc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/chat/$chatNumber'
    | '/doc/upload'
    | '/doc'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/doc'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/chat/$chatNumber'
    | '/doc/upload'
    | '/doc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  DocRoute: typeof DocRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc': {
      id: '/doc'
      path: '/doc'
      fullPath: '/doc'
      preLoaderRoute: typeof DocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatNumber': {
      id: '/chat/$chatNumber'
      path: '/$chatNumber'
      fullPath: '/chat/$chatNumber'
      preLoaderRoute: typeof ChatChatNumberRouteImport
      parentRoute: typeof ChatRoute
    }
    '/doc/': {
      id: '/doc/'
      path: '/'
      fullPath: '/doc/'
      preLoaderRoute: typeof DocIndexRouteImport
      parentRoute: typeof DocRoute
    }
    '/doc/upload': {
      id: '/doc/upload'
      path: '/upload'
      fullPath: '/doc/upload'
      preLoaderRoute: typeof DocUploadRouteImport
      parentRoute: typeof DocRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatNumberRoute: typeof ChatChatNumberRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatNumberRoute: ChatChatNumberRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface DocRouteChildren {
  DocUploadRoute: typeof DocUploadRoute
  DocIndexRoute: typeof DocIndexRoute
}

const DocRouteChildren: DocRouteChildren = {
  DocUploadRoute: DocUploadRoute,
  DocIndexRoute: DocIndexRoute,
}

const DocRouteWithChildren = DocRoute._addFileChildren(DocRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  DocRoute: DocRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
